package com.example.data.repository

import android.util.Log
import com.example.BuildConfig
import com.example.data.database.DashboardDao
import com.example.data.model.HistoryLog
import com.example.data.model.TelegramChannel
import com.example.data.model.UserProfile
import com.example.network.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext

class DashboardRepository(private val dao: DashboardDao) {

    val userProfile: Flow<UserProfile?> = dao.getUserProfile()
    val allTelegramChannels: Flow<List<TelegramChannel>> = dao.getAllTelegramChannels()
    val allHistoryLogs: Flow<List<HistoryLog>> = dao.getAllHistoryLogs()

    suspend fun updateProfile(profile: UserProfile) = withContext(Dispatchers.IO) {
        dao.insertOrUpdateProfile(profile)
    }

    suspend fun addTelegramChannel(channel: TelegramChannel) = withContext(Dispatchers.IO) {
        dao.insertTelegramChannel(channel)
    }

    suspend fun deleteTelegramChannel(channel: TelegramChannel) = withContext(Dispatchers.IO) {
        dao.deleteTelegramChannel(channel)
    }

    suspend fun deleteChannelById(id: Int) = withContext(Dispatchers.IO) {
        dao.deleteTelegramChannelById(id)
    }

    suspend fun addHistoryLog(toolName: String, prompt: String, output: String) = withContext(Dispatchers.IO) {
        dao.insertHistoryLog(
            HistoryLog(
                toolName = toolName,
                promptInput = prompt,
                generatedOutput = output
            )
        )
    }

    suspend fun clearHistory() = withContext(Dispatchers.IO) {
        dao.clearHistoryLogs()
    }

    // --- Gemini Content Generation ---
    suspend fun generateWithGemini(prompt: String, systemInstruction: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Error: Gemini API Key is missing. Please configure it in the Secrets panel."
        }

        val contentList = listOf(Content(parts = listOf(Part(text = prompt))))
        val instruction = systemInstruction?.let { Content(parts = listOf(Part(text = it))) }
        val request = GenerateContentRequest(contents = contentList, systemInstruction = instruction)

        try {
            val response = ApiClient.geminiService.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text 
                ?: "Empty output generated by AI model."
        } catch (e: Exception) {
            Log.e("DashboardRepository", "Gemini error: ", e)
            "Error matching query inputs: ${e.localizedMessage ?: e.message}"
        }
    }

    // --- Gemini Vision (Image analysis to prompt) ---
    suspend fun generateWithGeminiVision(prompt: String, base64Image: String): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Error: Gemini API Key is missing. Please configure it in the Secrets panel."
        }

        val request = GenerateContentRequest(
            contents = listOf(
                Content(
                    parts = listOf(
                        Part(text = prompt),
                        Part(inlineData = InlineData(mimeType = "image/jpeg", data = base64Image))
                    )
                )
            )
        )

        try {
            val response = ApiClient.geminiService.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                ?: "Empty description generated from image."
        } catch (e: Exception) {
            Log.e("DashboardRepository", "Gemini Vision error: ", e)
            "Error analyzing image: ${e.localizedMessage ?: e.message}"
        }
    }

    // --- Telegram Channel Messaging API ---
    suspend fun sendTelegramMessage(token: String, chatIdentifier: String, text: String): Boolean = withContext(Dispatchers.IO) {
        try {
            ApiClient.telegramService.sendMessage(
                token = token,
                chatId = chatIdentifier,
                text = text
            )
            true
        } catch (e: Exception) {
            Log.e("DashboardRepository", "Telegram Send Message Error: ", e)
            false
        }
    }

    suspend fun sendTelegramPhoto(token: String, chatIdentifier: String, photoUrl: String, caption: String?): Boolean = withContext(Dispatchers.IO) {
        try {
            ApiClient.telegramService.sendPhoto(
                token = token,
                chatId = chatIdentifier,
                photoUrl = photoUrl,
                caption = caption
            )
            true
        } catch (e: Exception) {
            Log.e("DashboardRepository", "Telegram Send Photo Error: ", e)
            false
        }
    }
}
